version: '3.8'

services:
  db:
    env_file:
      - .env
    build:
      context: .
      dockerfile: ./postgres/Dockerfile
    expose:
      - "5432"
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: symfony
      POSTGRES_USER: symfony
      POSTGRES_PASSWORD: symfony
      PGSSLROOTCERT: ${PGSSLROOTCERT}
      PGSSLCERT: ${PGSSLCERT}
      PGSSLKEY: ${PGSSLKEY}

    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U symfony" ]
      interval: 30s
      timeout: 60s
      retries: 5
      start_period: 80s

  php:
    env_file:
      - ./../../.env
    build:
      context: ../../
      dockerfile: ./examples/docker/php/Dockerfile
      target: 'application'
    depends_on:
      db:
        condition: service_healthy

  nginx:
    build:
      context: ./../../
      dockerfile: ./examples/docker/php/Dockerfile
      target: 'nginx'
    depends_on:
      php:
        condition: service_started
    ports:
      - "8000:8000"
volumes:
  postgres-data:

