version: '3.8'

services:
  db:
    image: postgres:11.5-alpine
    ports:
      - "54320:5432"
    environment:
      POSTGRES_DB: symfony
      POSTGRES_USER: symfony
      POSTGRES_PASSWORD: symfony

  php:
    env_file:
      - ./../../.env
    build:
      context: ../../
      dockerfile: ./examples/docker/php/Dockerfile

  nginx:
    build:
      context: ./../../
      dockerfile: ./examples/docker/nginx/Dockerfile
    ports:
      - "8000:8000"
